[target.'cfg(target_os = "linux")']
# Dramatically increases the link performance for the eventbus
rustflags = ["-C", "link-arg=-fuse-ld=lld"] # sudo apt -y install lld

[target.'cfg(target_os = "macos")']
# For faster link times ($ brew install michaeleisel/zld/zld )
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]

# Run time env. vars. see main.rs for usage
[env]
FOO = "bar"
XX = "42"
PATH_TO_SOME_TOOL = { value = "bin/tool", relative = true }
USERNAME = { value = "test_user", force = true }