name: clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: a
      run: rustup component add clippy --toolchain 1.72.1-x86_64-unknown-linux-gnu
    - name: Run clippy
      run: cargo clippy
